plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace "com.granitaistore.obddiagnostic"
    compileSdk 34

    defaultConfig {
        applicationId "com.granitaistore.obddiagnostic"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    // 🔴 ОЦЕ БУЛО ВІДСУТНЄ
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    // 🔴 І ОЦЕ ТЕЖ
    kotlinOptions {
        jvmTarget = "17"
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation 'com.github.PhilJay:MPAndroidChart:v3.1.0'

}
