name: 01 - Generate Release Keystore (ONE TIME)

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate JKS keystore
        run: |
          keytool -genkeypair \
            -keystore release.jks \
            -storetype JKS \
            -alias releasekey \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass password123 \
            -keypass password123 \
            -dname "CN=Opel Diagnostic, OU=Dev, O=GranIT, L=UA, S=UA, C=UA"

      - name: Verify keystore
        run: |
          keytool -list -keystore release.jks -storepass password123

      - name: Encode keystore
        run: |
          base64 release.jks > keystore_base64.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-keystore
          path: keystore_base64.txt
