name: Generate Release Keystore

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate keystore
        run: |
          keytool -genkeypair \
            -keystore opel_release.keystore \
            -alias opelkey \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass changeit \
            -keypass changeit \
            -dname "CN=Opel Diagnostic, OU=Dev, O=GranIT, L=UA, S=UA, C=UA"

      - name: Encode keystore
        run: |
          base64 opel_release.keystore > keystore_base64.txt

      - name: Upload keystore (TEMP)
        uses: actions/upload-artifact@v4
        with:
          name: keystore
          path: keystore_base64.txt
